[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["node_modules", "lib"]
optimizer = true
optimizer_runs = 20000
solc = "0.8.23"
via_ir = true

extra_output = ["storageLayout"]

remappings = [
  "forge-std/=node_modules/forge-std/src",
  "ds-test/=node_modules/ds-test/src",
  "src/=src",
  "test/=test",
  "@openzeppelin/=node_modules/@openzeppelin/",
  "@openzeppelin-upgrades/contracts/=node_modules/@openzeppelin/contracts-upgradeable",
  "erc6551/=node_modules/erc6551/",
  "solady/=node_modules/solady/",
  "@piplabs/story-contracts/interfaces/=../story/contracts/src/interfaces",
  "@piplabs/story-contracts/libraries/=../story/contracts/src/libraries",
]

fs_permissions = [
  { access = "read-write", path = "./test" },
  { access = "read-write", path = "./script" },
  { access = "read", path = "./out" },
  { access = "read-write", path = "./script/admin-actions/output/" },
]

[fuzz]
seed = "0x6eed"

[fmt]
bracket_spacing = true
number_underscore = "thousands"
